services:
  tts-discord-bot:
    container_name: tts-discord-bot
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh:/wsl-ssh:ro
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: db
    command: sleep infinity
    network_mode: service:db
    
  db:
    container_name: tts-discord-bot-pg
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
        - "5432"

  tts_bot_local_voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    expose:
      - 50021
    tty: true

volumes:
    postgres-data: